### ISSUE TITLE
Feature Request: Holding interact should speed up the text display

### ISSUE THREAD

**Issue by Wavesonics** [jacopofar/godot-easy-dialogue#14]
For impatient people :P

**Comment by jacopofar** [comment]
Ahah, good idea, I hate when games have long slowly typed texts.

**Comment by jacopofar** [comment]
I implemented it with a default skip of 300ms and a new tag `[set_skip X]` which allows one to change the skip interval (setting it to 0 disables the skip behavior).

Do you think this is fine?
