### ISSUE TITLE
Need signal for when dialog hides

### ISSUE THREAD

**Issue by Wavesonics** [jacopofar/godot-easy-dialogue#8]
Maybe I'm missing the intended way for this to work, but I need a signal to know when the user has dismissed the dialog box so I can do whatever the next thing is.

Is there some way this is intended to work? I just added a dialogue closed signal that is fired when hide is called which seems to work well.

**Comment by jacopofar** [comment]
Right now the intended way is to put a `[break something]` at the end of the text to get a signal, but now that you mention it (and reading the other issues) it would require the player to give two inputs to close it.

I think I'll add another signal for this. By the way feel free to make PRs if you want, these two days I'll be traveling so will not implement anything :)
